get_vars=["CURSUS_LMD",	"CYCLE",	"DEGETU",	"NATURE",	"NIVEAU",	"NIVEAU_D",	
 "NIVEAU_F",	"SECTDIS",	"TYP_DIPL",	"VOIE",	"DIPLOM",	"GROUPE",	"SPECIA",
 "SPECIB",	"SPECIC",	"PAR_TYPE", "ECHANG",   "DEPRESPA",	"PCSPAR",	"COMETA",	
 "ETABLI",	"ETABLI_DIFFUSION", "oppos",	"ANBAC",	"BAC",	"BAC_RGRP",	
 "BAC_SPE1",    "BAC_SPE2", "DEPBAC",	"ACABAC",	"ANNAIS",	"AGE",	"SEXE",	
 "NATION",	"PARIPA",	"COMINS",	"COMPOS",	"NUMED",	"EFFECTIF",	"NBACH",	
 "NET",	"INSPR",	"REGIME",	"AMENA",	"CONV",	"EXOINS",	"CURPAR",	"TYPREPA",	
 "DIPDER",	"SITUPRE",	"flag_meef",	"FLAG_SUP"]